apiVersion: apps/v1
kind: Deployment
metadata:
  name: goserver
  labels: 
    app: goserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: goserver
  template:
    metadata:
      labels: 
        app: goserver
    spec:
      containers: 
      - name: goserver
        image: andrevst/hello-go:0.7.3
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8000
          periodSeconds: 5
          failureThreshold: 1
          timeoutSeconds: 1
          successThreshold: 1
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8000
          periodSeconds: 3
          failureThreshold: 1
        startupProbe:
          httpGet:
            path: /healthz
            port: 8000
          periodSeconds: 3
          failureThreshold: 30
        envFrom:
          - configMapRef:
              name: goserver-env
          - secretRef:
              name: goserver-secret
        volumeMounts:
          - mountPath: "/myfamily"
            name: config
      volumes:
        - name: config
          configMap:
            name: configmap-family
            items:
            - key: members
              path: "family.txt"