apiVersion: apps/v1
kind: Deployment
metadata:
  name: goserver
  labels: 
    app: goserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: goserver
  template:
    metadata:
      labels: 
        app: goserver
    spec:
      containers: 
      - name: goserver
        image: andrevst/hello-go:0.5
        envFrom:
          - configMapRef:
              name: goserver-env
        volumeMounts:
          - mountPath: "/myfamily"
            name: config
      volumes:
        - name: config
          configMap:
            name: configmap-family
            items:
            - key: members
              path: "family.txt"