apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: goserver
  labels: 
    app: goserver
spec:
    replicas: 15
    selector:
      matchLabels:
        app: goserver
    template:
      metadata:
        labels: 
          app: "goserver"
      spec:
        containers: 
          - name: goserver
            image: "andrevst/hello-go:0.2"