apiVersion: v1
kind: Service
metadata:
  name: goserver-svc
spec:
  selector:
    app: goserver
  ports:
    - protocol: TCP
      port: 80 # This is the port the service is listening on
      targetPort: 8000 # This is the port the container is listening on
