version: '3'

services:
  node:
    build: ./app/
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    environment:
      MYSQL_USER: fullcycle
      MYSQL_PASSWORD: 12345qwerty
      MYSQL_DATABASE: mydb
    networks:
      - app-network


  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - node
    networks:
      - app-network


  mysql:
    image: mysql:latest
    platform: linux/arm64
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydb
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    networks:
      - app-network

networks:
  app-network: